force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievements including certifications and accomplishments.</description>
    <label>Achievement</label>
    <nameField>
        <label>Acheivement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Master relationship to Resume object.</description>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement__c/recordTypes/Accomplishment.recordType-meta.xml
<RecordType>
    <fullName>Accomplishment</fullName>
    <active>true</active>
    <description>Accomplishment achieved.</description>
    <label>Accomplishment</label>
</RecordType>

force-app/main/default/objects/Achievement__c/recordTypes/Certification.recordType-meta.xml
<RecordType>
    <fullName>Certification</fullName>
    <active>true</active>
    <description>Certification achieved</description>
    <label>Certification</label>
</RecordType>

force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description>Object that relates Account to Resume for Professional and Educational experiences.</description>
    <label>Experience</label>
    <nameField>
        <displayFormat>X-{0000}</displayFormat>
        <label>Experience Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <description>Professional Development course name.</description>
    <label>Course Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account record for the Experience.</description>
    <inlineHelpText>Enter in your Employer or Educational Institution.</inlineHelpText>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Master lookup to the Resume record.</description>
    <inlineHelpText>Resume record this experience is related to.</inlineHelpText>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Experience__c/recordTypes/Educational.recordType-meta.xml
<RecordType>
    <fullName>Educational</fullName>
    <active>true</active>
    <description>Educational Experience</description>
    <label>Educational</label>
</RecordType>

force-app/main/default/objects/Experience__c/recordTypes/Professional.recordType-meta.xml
<RecordType>
    <fullName>Professional</fullName>
    <active>true</active>
    <description>Professional Experience.</description>
    <label>Professional</label>
</RecordType>

force-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <customHelpPage>ResumeHelpPage</customHelpPage>
    <description>Contains data on the resume for a Contact.</description>
    <label>Resume</label>
    <nameField>
        <label>Resume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Technical_Skill__c/Technical_Skill__c.object-meta.xml
<CustomObject>
    <description>Technical Skills object</description>
    <label>Technical Skill</label>
    <nameField>
        <label>Technical Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Technical_Skill__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Master lookup to the Resume</description>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Technical Skills</relationshipLabel>
    <relationshipName>Technical_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ResumeControllerExtensionTest.cls
/* Test class for Controller Extension */
@isTest
public class ResumeControllerExtensionTest {
    
    //Test that the page renders with a Resume record   
    @isTest static void resumeControllerTestMethod() {
        //Call Data Factory to create Test Resume Record
        Resume__c tr = ResumeTestDataFactory.createTestResume();
        
        // Test Run        
        Test.startTest();
            //Call the Page and Controller. Pass the Id of test Resume 
            ApexPages.StandardController sc = new ApexPages.StandardController(tr);
            ResumeControllerExtension testResumeExt = new ResumeControllerExtension(sc);
            PageReference pageRef = Page.ResumePage;
            pageRef.getParameters().put('id', String.valueOf(tr.Id));
            
            //Test that the Skills records are returned in the correct order (sort order)
            testResumeExt.getTechnicalSkills();
            List<Technical_Skill__c> lstSkills = testResumeExt.technicalSkills;
            Technical_Skill__c[] skills = testResumeExt.technicalSkills;
            System.assertEquals('Skill 1', skills[0].Name);
            
            //Test that the Certification Achievement records are returned in the correct order (sort order)
            testResumeExt.getCertifications();
            List<Achievement__c> lstCerts = testResumeExt.certifications;
            Achievement__c[] certs = testResumeExt.certifications;
            System.assertEquals('Certification 1', certs[0].Name);

            //Test that the Accomplishment Achievement records are returned in the correct order (sort order)
            testResumeExt.getAccomplishments();
            List<Achievement__c> lstAccms = testResumeExt.accomplishments;
            Achievement__c[] accms = testResumeExt.accomplishments;
            System.assertEquals('Accomplishment 1', accms[0].Name);

            //Test that the Professional Development records are returned in the correct order (start date descending)    
            testResumeExt.getTrainingCourses();
            List <Experience__c> lstTrngs = testResumeExt.trainingCourses;
            Experience__c[] trngs = testResumeExt.trainingCourses;
            System.assertEquals('Training 1', trngs[0].Course_Name__c);
            
            //Test that the Professional Experience records are returned in the correct order (start date descending)    
            testResumeExt.getJobExperiences();
            List <Experience__c> lstJobs = testResumeExt.jobExperiences;
            Experience__c[] jobs = testResumeExt.jobExperiences;
            System.assertEquals('0 Company', jobs[0].Organization__r.Name);
                
            //Test that the Educational Experience records are returned in the correct order (start date descending)
            testResumeExt.getEduExperiences();	
            List <Experience__c> lstEdu = testResumeExt.eduExperiences;
            Experience__c[] eds = testResumeExt.eduExperiences;
            System.assertEquals('The University of the United States',eds[0].Organization__r.Name);
                
            Test.setCurrentPage(pageRef);
        Test.stopTest();   
    }
}