force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievements including certifications and accomplishments.</description>
    <label>Achievement</label>
    <nameField>
        <label>Acheivement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Master relationship to Resume object.</description>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement__c/recordTypes/Accomplishment.recordType-meta.xml
<RecordType>
    <fullName>Accomplishment</fullName>
    <active>true</active>
    <description>Accomplishment achieved.</description>
    <label>Accomplishment</label>
</RecordType>

force-app/main/default/objects/Achievement__c/recordTypes/Certification.recordType-meta.xml
<RecordType>
    <fullName>Certification</fullName>
    <active>true</active>
    <description>Certification achieved</description>
    <label>Certification</label>
</RecordType>

force-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <customHelpPage>ResumeHelpPage</customHelpPage>
    <description>Contains data on the resume for a Contact.</description>
    <label>Resume</label>
    <nameField>
        <label>Resume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateAchievementRTsTest.cls
@isTest
public class UpdateAchievementRTsTest {
    static testMethod void test(){
        //Call Data Factory to create Test Resume Record
        Resume__c tr = ResumeTestDataFactory.createTestResume();
        Test.startTest();
            // Call UpdateExperienceRT batch to update record types
            UpdateAchievementRTs uacv = new UpdateAchievementRTs();
            Id acvBatchId = Database.executeBatch(uacv);
        Test.stopTest();
        // The Data Factory creates 4 Accomplishment and 3 Certifications, this validates that those records have the correct record type.
        System.assertEquals(4, [SELECT count() FROM Achievement__c WHERE RecordType.Name = 'Accomplishment']);
        System.assertEquals(3, [SELECT count() FROM Achievement__c WHERE RecordType.Name = 'Certification']);
    }
}