force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievements including certifications and accomplishments.</description>
    <label>Achievement</label>
    <nameField>
        <label>Acheivement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <description>Date field for documenting when the Achievement was completed.</description>
    <label>Completion Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Master relationship to Resume object.</description>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Order in which the user wants the achievements sorted</description>
    <inlineHelpText>Enter in the sort order for the achievement.</inlineHelpText>
    <label>Sort Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <description>Captures the venue and location text.</description>
    <inlineHelpText>Enter in the venue or org, and location</inlineHelpText>
    <label>Subtitle</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Achievement__c/recordTypes/Accomplishment.recordType-meta.xml
<RecordType>
    <fullName>Accomplishment</fullName>
    <active>true</active>
    <description>Accomplishment achieved.</description>
    <label>Accomplishment</label>
</RecordType>

force-app/main/default/objects/Achievement__c/recordTypes/Certification.recordType-meta.xml
<RecordType>
    <fullName>Certification</fullName>
    <active>true</active>
    <description>Certification achieved</description>
    <label>Certification</label>
</RecordType>

force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description>Object that relates Account to Resume for Professional and Educational experiences.</description>
    <label>Experience</label>
    <nameField>
        <displayFormat>X-{0000}</displayFormat>
        <label>Experience Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <description>Date of experience completion.</description>
    <inlineHelpText>Enter in the date completed (Day of month is not important).</inlineHelpText>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Completion_Date_Text__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Text__c</fullName>
    <description>Date of Experience record completion in Month Year format</description>
    <formula>CASE(MONTH(Completion_Date__c),
	1, &quot;January&quot;,
	2, &quot;February&quot;,
	3, &quot;March&quot;, 
	4, &quot;April&quot;, 
	5, &quot;May&quot;, 
	6, &quot;June&quot;,
	7, &quot;July&quot;,
	8, &quot;August&quot;,
	9, &quot;September&quot;,
	10, &quot;October&quot;,
	11, &quot;November&quot;,
	12, &quot;December&quot;,
	&quot;&quot;)
&amp;&quot; &quot;&amp;TEXT(YEAR(Completion_Date__c))</formula>
    <label>Completion Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <description>Professional Development course name.</description>
    <label>Course Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Degree_Earned__c.field-meta.xml
<CustomField>
    <fullName>Degree_Earned__c</fullName>
    <description>Degree earned from experience</description>
    <label>Degree Earned</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Rich-Text field contains the details on the experience.</description>
    <label>Description</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Experience_Span__c.field-meta.xml
<CustomField>
    <fullName>Experience_Span__c</fullName>
    <description>Formula field calculates the date range for an experience and returns it in Month (text) Year format.</description>
    <formula>CASE(MONTH(Start_Date__c),
	1, &quot;January&quot;,
	2, &quot;February&quot;,
	3, &quot;March&quot;, 
	4, &quot;April&quot;, 
	5, &quot;May&quot;, 
	6, &quot;June&quot;,
	7, &quot;July&quot;,
	8, &quot;August&quot;,
	9, &quot;September&quot;,
	10, &quot;October&quot;,
	11, &quot;November&quot;,
	12, &quot;December&quot;,
	&quot;&quot;)
&amp;&quot; &quot;&amp;TEXT(YEAR(Start_Date__c))
&amp; &quot; - &quot; &amp;
IF(
	ISBLANK(End_Date__c),
	&quot;Present&quot;,CASE(MONTH(End_Date__c),
	1, &quot;January&quot;,
	2, &quot;February&quot;,
	3, &quot;March&quot;, 
	4, &quot;April&quot;, 
	5, &quot;May&quot;, 
	6, &quot;June&quot;,
	7, &quot;July&quot;,
	8, &quot;August&quot;,
	9, &quot;September&quot;,
	10, &quot;October&quot;,
	11, &quot;November&quot;,
	12, &quot;December&quot;,
	&quot;&quot;) 
	&amp;&quot; &quot; &amp; TEXT(YEAR(End_Date__c))
)</formula>
    <label>Tenure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>Job title held for experience</description>
    <label>Job Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Experience location.</description>
    <inlineHelpText>Leave blank if the same as company address. This will be automatically populated.</inlineHelpText>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account record for the Experience.</description>
    <inlineHelpText>Enter in your Employer or Educational Institution.</inlineHelpText>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Master lookup to the Resume record.</description>
    <inlineHelpText>Resume record this experience is related to.</inlineHelpText>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of the experience.</description>
    <inlineHelpText>Start date of the experience (day is not important).</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Experience__c/recordTypes/Educational.recordType-meta.xml
<RecordType>
    <fullName>Educational</fullName>
    <active>true</active>
    <description>Educational Experience</description>
    <label>Educational</label>
</RecordType>

force-app/main/default/objects/Experience__c/recordTypes/Professional.recordType-meta.xml
<RecordType>
    <fullName>Professional</fullName>
    <active>true</active>
    <description>Professional Experience.</description>
    <label>Professional</label>
</RecordType>

force-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <customHelpPage>ResumeHelpPage</customHelpPage>
    <description>Contains data on the resume for a Contact.</description>
    <label>Resume</label>
    <nameField>
        <label>Resume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Technical_Skill__c/Technical_Skill__c.object-meta.xml
<CustomObject>
    <description>Technical Skills object</description>
    <label>Technical Skill</label>
    <nameField>
        <label>Technical Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Technical_Skill__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Master lookup to the Resume</description>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Technical Skills</relationshipLabel>
    <relationshipName>Technical_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Technical_Skill__c/fields/Skills_List__c.field-meta.xml
<CustomField>
    <fullName>Skills_List__c</fullName>
    <description>List of skills.</description>
    <inlineHelpText>Enter in the skills.</inlineHelpText>
    <label>Skills List</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Technical_Skill__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Order in which the user wants the Technical Skills sorted.</description>
    <label>Sort Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ResumeControllerExtension.cls
/****************************************************************************************
* ResumeController extension allows for custom lists for the Resume visualforce pages 	*
* Authored by Jacques Grillot for the SfResume App										*
* *************************************************************************************/
// Public class with res variable to accept Resume__c id
Public with sharing class ResumeControllerExtension {
    private final Resume__c res;
    
    public resumeControllerExtension(ApexPages.StandardController stdController){
        this.res = (Resume__c)stdController.getRecord();
    }
    
    // Declare a list for "Certification" achievements
    Public List<Achievement__c> certifications {get;set;}
    // Instantiate the get method to query Certifications
    Public List<Achievement__c> getCertifications(){
        if(certifications == null) certifications = [SELECT Id, Name, Sort_Order__c 
                                                     FROM Achievement__c 
                                                     WHERE Resume__r.Id= :res.Id AND RecordType.Name = 'Certification'
                                                     ORDER BY Sort_Order__c];    
        //Return the Certification list so the records can be rendered in the Page
        return certifications;
    }
    
    //Declare a list for "Professional" experiences
    Public List<Experience__c> jobExperiences {get;set;}
    //Instantiate a get method to query the Professional experiences
    Public List<Experience__c> getJobExperiences(){
        if (jobExperiences == null) jobExperiences = [SELECT Id, Job_Title__c, Experience_Span__c, Organization__r.Name, Description__c, Location__c, Start_Date__c 
                                                      FROM Experience__c
                                                      WHERE Resume__r.Id= :res.Id
                                                      AND RecordType.Name = 'Professional'
                                                      ORDER BY Start_Date__c DESC];
        //Return the Job Experience list so the records can be rendered in the Page
        return jobExperiences;
    }
    
    //Declare a list for "Educational" experiences
    Public List<Experience__c> eduExperiences {get;set;}
    //Instantiate a get method to query the Educational experiences
    Public List<Experience__c> getEduExperiences(){
        if (eduExperiences == null) eduExperiences = [SELECT Id, Degree_Earned__c, Completion_Date_Text__c, Organization__r.Name, Description__c, Location__c 
                                                      FROM Experience__c
                                                      WHERE Resume__r.Id= :res.Id
                                                      AND RecordType.Name = 'Educational'
                                                      ORDER BY Start_Date__c DESC];
        //Return the Educational Experience list so the records can be rendered in the Page
        return eduExperiences;
    }
    
    // Declare a list for "Training Courses" experiences
    Public List<Experience__c> trainingCourses {get;set;}
    // Instantiate the get method to query Professional Development experiences as Training Courses
    Public List<Experience__c> getTrainingCourses(){
        if(trainingCourses == null) trainingCourses = [SELECT Id, RecordType.Name, Course_Name__c, Completion_Date__c, Location__c, Organization__r.Name 
                                                       FROM Experience__c
                                                       WHERE Resume__r.Id= :res.Id AND RecordType.Name ='Professional Development' 
                                                       ORDER BY Completion_Date__c DESC];
        //Return the Training Course list so the records can be rendered in the Page
        return trainingCourses;
    }
    
    // Declare a list for "Accomplishment" achievements
    Public List<Achievement__c> accomplishments {get;set;}
    // Instantiate the get method to query Accomplishments
    Public List<Achievement__c> getAccomplishments(){
        if(accomplishments == null) accomplishments = [SELECT Id, Name, Subtitle__c, Completion_Date__c, Sort_Order__c 
                                                       FROM Achievement__c 
                                                       WHERE Resume__r.Id= :res.Id AND RecordType.Name ='Accomplishment' 
                                                       ORDER BY Sort_Order__c];
        //Return the Accomplishment list so the records can be rendered in the Page
        return accomplishments;
    }
    
    // Declare a list for Technical Skills
    Public List <Technical_Skill__c> technicalSkills {get;set;}
    // Instantiate the get method to query Technical Skills
    Public List <Technical_Skill__c> getTechnicalSkills(){
        if(technicalSkills == null) technicalSkills = [SELECT Id, Name, Skills_List__c, Sort_Order__c 
                                                       FROM Technical_Skill__c 
                                                       WHERE Resume__r.Id= :res.Id
                                                       ORDER BY Sort_Order__c];
        //Return the Technical Skill list so the records can be rendered in the Page
        return technicalSkills;
    }
}