force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievements including certifications and accomplishments.</description>
    <label>Achievement</label>
    <nameField>
        <label>Acheivement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <description>Date field for documenting when the Achievement was completed.</description>
    <label>Completion Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Master relationship to Resume object.</description>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Order in which the user wants the achievements sorted</description>
    <inlineHelpText>Enter in the sort order for the achievement.</inlineHelpText>
    <label>Sort Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement__c/recordTypes/Accomplishment.recordType-meta.xml
<RecordType>
    <fullName>Accomplishment</fullName>
    <active>true</active>
    <description>Accomplishment achieved.</description>
    <label>Accomplishment</label>
</RecordType>

force-app/main/default/objects/Achievement__c/recordTypes/Certification.recordType-meta.xml
<RecordType>
    <fullName>Certification</fullName>
    <active>true</active>
    <description>Certification achieved</description>
    <label>Certification</label>
</RecordType>

force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description>Object that relates Account to Resume for Professional and Educational experiences.</description>
    <label>Experience</label>
    <nameField>
        <displayFormat>X-{0000}</displayFormat>
        <label>Experience Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <description>Date of experience completion.</description>
    <inlineHelpText>Enter in the date completed (Day of month is not important).</inlineHelpText>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <description>Professional Development course name.</description>
    <label>Course Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Degree_Earned__c.field-meta.xml
<CustomField>
    <fullName>Degree_Earned__c</fullName>
    <description>Degree earned from experience</description>
    <label>Degree Earned</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Rich-Text field contains the details on the experience.</description>
    <label>Description</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of the experience</description>
    <inlineHelpText>Enter in the end date of the experience (day of month is not important)</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>Job title held for experience</description>
    <label>Job Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Experience location.</description>
    <inlineHelpText>Leave blank if the same as company address. This will be automatically populated.</inlineHelpText>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account record for the Experience.</description>
    <inlineHelpText>Enter in your Employer or Educational Institution.</inlineHelpText>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Master lookup to the Resume record.</description>
    <inlineHelpText>Resume record this experience is related to.</inlineHelpText>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of the experience.</description>
    <inlineHelpText>Start date of the experience (day is not important).</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Experience__c/recordTypes/Educational.recordType-meta.xml
<RecordType>
    <fullName>Educational</fullName>
    <active>true</active>
    <description>Educational Experience</description>
    <label>Educational</label>
</RecordType>

force-app/main/default/objects/Experience__c/recordTypes/Professional.recordType-meta.xml
<RecordType>
    <fullName>Professional</fullName>
    <active>true</active>
    <description>Professional Experience.</description>
    <label>Professional</label>
</RecordType>

force-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <customHelpPage>ResumeHelpPage</customHelpPage>
    <description>Contains data on the resume for a Contact.</description>
    <label>Resume</label>
    <nameField>
        <label>Resume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Boolean field to flag whether the resume is active. If unchecked, the Visualforce resume's will not render.</description>
    <inlineHelpText>If unchecked, the Visualforce resume's will not render.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Master lookup to the Contact record. In the context where a user will have access to the resume of the contact they create, not necessarily the resume of others.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resumes</relationshipLabel>
    <relationshipName>Resumes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <description>Resume summary contains the a summary of qualifications</description>
    <inlineHelpText>Enter in the summary of your qualifications for the position.</inlineHelpText>
    <label>Summary</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Technical_Skill__c/Technical_Skill__c.object-meta.xml
<CustomObject>
    <description>Technical Skills object</description>
    <label>Technical Skill</label>
    <nameField>
        <label>Technical Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Technical_Skill__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Master lookup to the Resume</description>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Technical Skills</relationshipLabel>
    <relationshipName>Technical_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Technical_Skill__c/fields/Skills_List__c.field-meta.xml
<CustomField>
    <fullName>Skills_List__c</fullName>
    <description>List of skills.</description>
    <inlineHelpText>Enter in the skills.</inlineHelpText>
    <label>Skills List</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Technical_Skill__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Order in which the user wants the Technical Skills sorted.</description>
    <label>Sort Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ResumeTestDataFactory.cls
@isTest
public class ResumeTestDataFactory {
    public static Resume__c createTestResume(){
        
        //Create a Test Contact
        Contact testContact = new Contact (FirstName='Ferris', LastName='Bueller', MailingCity='Chicago', MailingState='Il');
        System.debug('Contact ' + testContact.FirstName + ' ' + testContact.LastName + ' created');
        insert testContact;
        
        //Create a Test Resume
        Resume__c testResume = new Resume__c (Contact__c = testContact.Id, Name='Sf Admin', Active__c = true, Summary__c='I am an #AwesomeAdmin, hire me!');
        System.debug('Resume ' + testResume.Name + ' created');
        insert testResume;
        
        //Create 3 Test Technical Skills with a decremental sort order so the controller will re-sort
        List<Technical_Skill__c> testSkills = new List<Technical_Skill__c>();
        for (integer t=3; t>0; t--){
            testSkills.add(new Technical_Skill__c(Name='Skill ' + t,
                                                  Resume__c = testResume.Id,
                                                  Skills_List__c = 'Apex ' + t,
                                                  Sort_Order__c = t));
        }
        insert testSkills;
        
        //Create 3 Test Certifications with a decremental sort order so the controller will re-sort
        //First query the RecordTypeId to use for the test record
        Id RecordTypeIdCert = Schema.SObjectType.Achievement__c.getRecordTypeInfosByName().get('Certification').getRecordTypeId();
        List<Achievement__c> testCerts = new List<Achievement__c>();
        for (integer t=3; t>0; t--){
            testCerts.add(new Achievement__c (Name='Certification ' + t,
                                              Resume__c = testResume.Id,
                                              RecordTypeId = RecordTypeIdCert,
                                              Completion_Date__c = System.today(),
                                              Sort_Order__c = t));
        }
        insert testCerts;
        
        //Create 3 Test Accomplishments with a decremental sort order so the controller will re-sort
        Id RecordTypeIdAccm = Schema.SObjectType.Achievement__c.getRecordTypeInfosByName().get('Accomplishment').getRecordTypeId();
        List<Achievement__c> testAccms = new List<Achievement__c>();
        for (integer t=3; t>0; t--){
            testAccms.add(new Achievement__c (Name='Accomplishment ' + t,
                                              Resume__c = testResume.Id,
                                              RecordTypeId = RecordTypeIdAccm,
                                              Completion_Date__c = System.today(),
                                              Sort_Order__c = t));
        }
        insert testAccms;
        
        //Create 3 Test Training Courses with Completed date as many month completed before todays date by the number of the counter 
        Id RecordTypeIdTrn = Schema.SObjectType.Experience__c.getRecordTypeInfosByName().get('Professional Development').getRecordTypeId();
        List<Experience__c> testTrngs = new List<Experience__c>();
        for (integer g=3; g>0; g--){
            testTrngs.add(new Experience__c(Course_Name__c ='Training ' + g,
                                            Resume__c = testResume.Id,
                                            RecordTypeId = RecordTypeIdTrn,
                                            Completion_Date__c = System.today().addMonths(-g),
                                            Location__c = 'San Francisco, CA'));
        }
        insert testTrngs;
        
        //Create an Education Institution
        Id RecordTypeIdUni = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Education Organization').getRecordTypeId();
        Account testUni = new Account( RecordTypeId = RecordTypeIdUni, Name='The University of the United States', BillingCity='Queens', BillingState='NY' );
        insert testUni;
        // Create a Test Degree
        Id RecordTypeIdEdu = Schema.SObjectType.Experience__c.getRecordTypeInfosByName().get('Educational').getRecordTypeId();
        List<Experience__c> testEdus = new List<Experience__c>();
        for (integer u=0; u<1; u++){
            testEdus.add(new Experience__c(RecordTypeId = RecordTypeIdEdu,
                                           Resume__c = testResume.Id,
                                           Organization__c= testUni.Id,
                                           Degree_Earned__c='BS Comp Sci',
                                           Completion_Date__c = System.today().addYears(-1),
                                           Description__c = 'Test'));
        }
        insert testEdus;
        
        // Create 3 Professional Organization Accounts
        Id RecordTypeIdPro = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Professional Organization').getRecordTypeId();
        List<Account> testPros = new List<Account>();
        for (integer p=0; p<3; p++){
            testPros.add(new Account(RecordTypeId = RecordTypeIdPro, 
                                     Name= p + ' Company', 
                                     BillingCity='Chicago' + p,
                                     BillingState='Il' ));
        }
        insert testPros;
        // Create Jobs with the End Date equal to today minus the counter's number of years. The Start date will be 1 year prior. Assign the org from the previous list by counter.
        Id RecordTypeIdJob = Schema.SObjectType.Experience__c.getRecordTypeInfosByName().get('Professional').getRecordTypeId();
        List<Experience__c> testJobs = new List<Experience__c>();
        for (integer u=2; u>=0; u--){
            integer y = u-1;
            testJobs.add(new Experience__c(RecordTypeId = RecordTypeIdJob,
                                           Resume__c = testResume.Id,
                                           Organization__c= testPros[0].Id,
                                           Job_Title__c = 'Job' + u,
                                           Description__c = 'Test',
                                          Start_Date__c = System.today().addYears(-y),
                                          End_Date__c = System.today().addYears(-u)));
        }
        insert testJobs;
                
        // Return the Resume Record
        return testResume;
    }
}