force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description>Object that relates Account to Resume for Professional and Educational experiences.</description>
    <label>Experience</label>
    <nameField>
        <displayFormat>X-{0000}</displayFormat>
        <label>Experience Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Master lookup to the Resume record.</description>
    <inlineHelpText>Resume record this experience is related to.</inlineHelpText>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Experience__c/recordTypes/Professional.recordType-meta.xml
<RecordType>
    <fullName>Professional</fullName>
    <active>true</active>
    <description>Professional Experience.</description>
    <label>Professional</label>
</RecordType>

force-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <customHelpPage>ResumeHelpPage</customHelpPage>
    <description>Contains data on the resume for a Contact.</description>
    <label>Resume</label>
    <nameField>
        <label>Resume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateExperienceRTsTest.cls
@isTest
public class UpdateExperienceRTsTest {
    static testMethod void test(){
        //Call Data Factory to create Test Resume Record
        Resume__c tr = ResumeTestDataFactory.createTestResume();
        Test.startTest();
        UpdateExperienceRTs ue = new UpdateExperienceRTs();
        Id batchId = Database.executeBatch(ue);
        Test.stopTest();
        System.assertEquals(3, [SELECT count() FROM Experience__c WHERE RecordType.Name = 'Professional Development']);
    }
}