force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description>Object that relates Account to Resume for Professional and Educational experiences.</description>
    <label>Experience</label>
    <nameField>
        <displayFormat>X-{0000}</displayFormat>
        <label>Experience Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <description>Professional Development course name.</description>
    <label>Course Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Degree_Earned__c.field-meta.xml
<CustomField>
    <fullName>Degree_Earned__c</fullName>
    <description>Degree earned from experience</description>
    <label>Degree Earned</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>Job title held for experience</description>
    <label>Job Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <description>Master lookup to the Resume record.</description>
    <inlineHelpText>Resume record this experience is related to.</inlineHelpText>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Experience__c/recordTypes/Educational.recordType-meta.xml
<RecordType>
    <fullName>Educational</fullName>
    <active>true</active>
    <description>Educational Experience</description>
    <label>Educational</label>
</RecordType>

force-app/main/default/objects/Experience__c/recordTypes/Professional.recordType-meta.xml
<RecordType>
    <fullName>Professional</fullName>
    <active>true</active>
    <description>Professional Experience.</description>
    <label>Professional</label>
</RecordType>

force-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <customHelpPage>ResumeHelpPage</customHelpPage>
    <description>Contains data on the resume for a Contact.</description>
    <label>Resume</label>
    <nameField>
        <label>Resume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateExperienceRTs.cls
/* This Class will update Experience "Education Experience" and "Professional Development" record types to the proper type based on the Experience's data
To execute run the below script through Execute Anonymous in the Dev Console:

UpdateExperienceRTs batchExperiences = new UpdateExperienceRTs(); 
Id batchId = Database.executeBatch(batchExperiences);

*/
public class UpdateExperienceRTs implements Database.Batchable<sObject>, Database.Stateful {
    // track number records processed
    public Integer recordsProcessed = 0;
    
    // locator start method to query all experience records
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(
            // sort experience records by Resume since they are detail - prevent future locking
          'SELECT Id, Resume__c, RecordTypeId, Course_Name__c, Job_Title__c, Degree_Earned__c FROM Experience__c ORDER BY Resume__c'  
        );
    }
    public void execute(Database.BatchableContext bc, List<Experience__c> scope){
        //process each batch of records
        // query record types to change to. 
        Id RecordTypeIdEdu = Schema.SObjectType.Experience__c.getRecordTypeInfosByName().get('Educational').getRecordTypeId();
        Id RecordTypeIdPrDv = Schema.SObjectType.Experience__c.getRecordTypeInfosByName().get('Professional Development').getRecordTypeId();
        Id RecordTypeIdProf = Schema.SObjectType.Experience__c.getRecordTypeInfosByName().get('Professional').getRecordTypeId();
        // Declare and instantiate a new list to store updated experience records
        List <Experience__c> experiences = new List<Experience__c>();
        for (Experience__c experience : scope){
            // Records with the Degree earned field populated are Educational experiences. Increment counter by 1 for each record processed.
            if(experience.Degree_Earned__c != null){
            	experience.RecordTypeId = RecordTypeIdEdu;
            	experiences.add(experience);
                recordsProcessed = recordsProcessed + 1;
            } 
            // Records with the Course Name field populated are Professoinal development experiences. Increment counter by 1 for each record processed.
            else if (experience.Course_Name__c != null){
                experience.RecordTypeId = RecordTypeIdPrDv;
                experiences.add(experience);
                recordsProcessed = recordsProcessed + 1;
            }
            else{
                experience.RecordTypeId = RecordTypeIdProf;
                experiences.add(experience);
                recordsProcessed = recordsProcessed + 1;
            }
        }
        // Update all records processed.
        update experiences;
    }
    public void finish(Database.BatchableContext bc){
        //Return number of records processed to debug log.
        System.debug(recordsProcessed + ' Experience records processed.');
    }
}